# pull official base image
FROM node:12 as build

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json /usr/src/app
COPY yarn.lock /usr/src/app
RUN yarn install

# add app
COPY . /usr/src/app

# build app
RUN yarn build

#NGINX Server

FROM nginx:1.15
COPY --from=build /usr/src/app/build/ /usr/share/nginx/html
# Copy nginx.config
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]