version: "3.8"
services:
    postgres:
        container_name: postgres
        image: postgres:11-alpine
        restart: always
        env_file: docker.env
        environment:
            PGDATA: /var/lib/postgresql/data/dbdata
        ports: 
            - 5432:5432
        volumes:
            - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
            - dbdata:/var/lib/postgresql/data
    
    web:
        container_name: web
        build: ./frontend
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - "3000:3000"
        command: bash -c "yarn && yarn start"
        links:
            - api
        restart: always
        stdin_open: true

    api:
        container_name: api
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/usr/src/app
        links:
            - postgres
            - redis:redis
        depends_on: 
            - postgres
            - redis
        env_file: docker.env
        environment:
            - DEV=1
        command: bash -c "diesel setup && cargo watch -x run"
        restart: always
    
    redis:
        container_name: redis
        image: redis:alpine
        expose:
            - 6379
        ports:
            - "6379:6379"

volumes:
    dbdata: