version: "3.1"
services:
    db:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: zachn
            POSTGRES_USER: zachn
            POSTGRES_DB: cico
            PGDATA: /var/lib/postgresql/data/dbdata
        ports: 
            - 5432:5432
        volumes:
            - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
            - dbdata:/var/lib/postgresql/data
    
    api:
        build: ./backend
        ports:
            - "3001:3001"
        volumes:
            - ./backend:/usr/src/app
        links:
            - db
        command: bash -c "diesel setup && cargo watch -x run"
    
    web:
        build: ./frontend
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - "3000:3000"
        command: bash -c "yarn && yarn start"
        links:
            - api

volumes:
    dbdata: