version: "3.8"
services:
    web:
        container_name: web
        build: ./frontend
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - "3000:3000"
        command: bash -c "yarn && yarn start"
        links:
            - api
        restart: always
        stdin_open: true

    api:
        container_name: api
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/usr/src/app
        links:
            - redis:redis
        depends_on:
            - redis
        command: bash -c "cargo watch -x run"
        restart: always
    
    redis:
        container_name: redis
        image: redis:alpine
        expose:
            - 6379
        ports:
            - "6379:6379"