version: "3.1"
services:
    postgres:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: zachn
            POSTGRES_USER: zachn
            POSTGRES_DB: cico
        ports: 
            - 5432:5432